version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    env_file:
      .env
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
  web:
    build:
      context: .
    command: ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: